### ISSUE TITLE
Player remains in spectator after join

### ISSUE THREAD

**Issue by PalmarHealer** [PalmarHealer/CustomBlocks#1]
The players gamemode is not restored if he leaves during the load phase.

**Comment by MistakingManx** [comment]
This issue also occurs if the resource pack fails to download, and grants the player full mobility in spectator.

Relevant error log;
```
[23:07:27 ERROR]: Could not pass event PlayerResourcePackStatusEvent to CustomBlocks v1.1
java.lang.ClassCastException: class de.nauren.customblocks.events.ResourcePackStatus cannot be cast to class org.bukkit.plugin.Plugin (de.nauren.customblocks.events.ResourcePackStatus is in unnamed module of loader 'CustomBlocks-1.1.jar' @407b22af; org.bukkit.plugin.Plugin is in unnamed module of loader java.net.URLClassLoader @7591083d)
        at CustomBlocks-1.1.jar/de.nauren.customblocks.events.ResourcePackStatus.onResourcePackStatus(ResourcePackStatus.java:58) ~[CustomBlocks-1.1.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:71) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21.8-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleResourcePackResponse(ServerGamePacketListenerImpl.java:3671) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:30) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.network.protocol.common.ServerboundResourcePackPacket.handle(ServerboundResourcePackPacket.java:9) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:29) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:155) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1449) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:176) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:129) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1429) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1423) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:139) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1380) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1388) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1265) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:310) ~[paper-1.21.8.jar:1.21.8-25-846c64f]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
